import { Clue, Suspect } from "./types";

export const initialClues: Clue[] = [
  {
    id: "clue_jack_stapleton",
    title: "Jack Stapleton Profile",
    type: "location",
    description: "Resident of Merripit House on the moor. Outwardly a harmless naturalist, but his knowledge of the Grimpen Mire and interest in the Baskerville lineage warrants scrutiny.",
    exhibitCode: "DOSSIER-STAPLETON",
    quote: "A small, slim, clean-shaven, prim-faced man... carrying a butterfly-net.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQ8u2qbeHTYvYPXb36MOW1qUR-8LTVkK54d6NmMKZ9V0NnVHwgOqQfrwwe9x3POchDC87DTI1Gl2sC3vjIqTqyinSu2NTNbKE9tpPb0z3DdLSy9IHy9tMlvfGYYYnAIem1ZuWd5WCGKNure9GtbUJhvdsiQgXfqrTm-F7iPiPoz_VMsCwnXTOePnFiaMuC6rBE8OunQ0_w0yZhmt7GrH8vRb5lJcxyVYQzYPvcv2V9ZS4GhW5Te6-oVZJj5xtT5v9QgEgG1pGgF1eF",
    coordinates: { x: 68, y: 35 },
    connections: ["clue_exhibit_a4", "clue_burned_letter"],
    metadata: {
      source: "Local Parish Records",
      threat: "HIGH",
      timestamp: "1888-09-24",
      domain: "merripit-naturalist.net",
    },
  },
  {
    id: "clue_exhibit_a4",
    title: "The Anonymous Warning",
    type: "physical",
    description: "An anonymous warning letter delivered to Sir Henry Baskerville in London, compiled from newsprint letters pasted on a sheet of paper.",
    exhibitCode: "EXHIBIT A-4",
    quote: "Keep away from the moor in the hours of darkness...",
    coordinates: { x: 28, y: 62 },
    connections: ["clue_jack_stapleton", "clue_london_warning"],
    metadata: {
      source: "Postmarked London",
      threat: "MEDIUM",
      timestamp: "1888-09-18",
    },
  },
  {
    id: "clue_hound_footprint",
    title: "Giant Hound Footprint",
    type: "physical",
    description: "A gigantic footprint found in the damp soil near the yew alley gate where Sir Charles Baskerville suffered his fatal heart collapse.",
    exhibitCode: "EXHIBIT B-1",
    quote: "Dr. Mortimer, did you see footprints? - Yes. - Of a man or of a woman? - Mr. Holmes, they were the footprints of a gigantic hound!",
    coordinates: { x: 50, y: 55 },
    connections: ["clue_exhibit_a4"],
    metadata: {
      source: "Yew Alley, Baskerville Hall",
      threat: "CRITICAL",
      timestamp: "1888-06-14",
    },
  },
  {
    id: "clue_burned_letter",
    title: "Laura Lyons Letter Fragment",
    type: "physical",
    description: "A charred fragment of a letter recovered from the fireplace at Baskerville Hall, bearing the initials 'L.L.'",
    exhibitCode: "EXHIBIT C-3",
    quote: "Please, please, as you are a gentleman, burn this letter, and be at the gate by ten o'clock.",
    coordinates: { x: 42, y: 25 },
    connections: ["clue_jack_stapleton"],
    metadata: {
      source: "Baskerville Fireplace",
      threat: "HIGH",
      timestamp: "1888-10-02",
      email: "lyons.laura@coombetracey.org",
    },
  },
  {
    id: "clue_missing_boot",
    title: "The Missing Brown Boot",
    type: "physical",
    description: "A newly purchased brown boot belonging to Sir Henry Baskerville went missing from his London hotel room, only to be replaced later by an old black boot.",
    exhibitCode: "EXHIBIT D-12",
    quote: "It was an old, well-worn boot, but of the same size. He wants Sir Henry's scent...",
    coordinates: { x: 22, y: 40 },
    connections: ["clue_hound_footprint"],
    metadata: {
      source: "Devonshire Private Hotel, London",
      threat: "MEDIUM",
      timestamp: "1888-09-20",
    },
  },
  {
    id: "clue_london_warning",
    title: "The Cab Spy Ledger",
    type: "witness",
    description: "A report from John Clayton, London cabdriver. He drove a man with a heavy dark beard who claimed to be 'Sherlock Holmes' and was spying on Sir Henry in Regent Street.",
    exhibitCode: "INTEL-09",
    quote: "He had a black beard, and he looked like he was about thirty years of age...",
    coordinates: { x: 15, y: 18 },
    connections: ["clue_exhibit_a4"],
    metadata: {
      source: "London Yard Interview",
      threat: "LOW",
      timestamp: "1888-09-21",
      ip: "188.42.12.221",
    },
  },
];

export const initialSuspects: Suspect[] = [
  {
    id: "sus_stapleton",
    name: "Jack Stapleton",
    occupation: "Naturalist & Butterfly Collector",
    status: "Suspect",
    threatLevel: "High",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQ8u2qbeHTYvYPXb36MOW1qUR-8LTVkK54d6NmMKZ9V0NnVHwgOqQfrwwe9x3POchDC87DTI1Gl2sC3vjIqTqyinSu2NTNbKE9tpPb0z3DdLSy9IHy9tMlvfGYYYnAIem1ZuWd5WCGKNure9GtbUJhvdsiQgXfqrTm-F7iPiPoz_VMsCwnXTOePnFiaMuC6rBE8OunQ0_w0yZhmt7GrH8vRb5lJcxyVYQzYPvcv2V9ZS4GhW5Te6-oVZJj5xtT5v9QgEgG1pGgF1eF",
    quote: "\"It is a lovely place, the moor, if you only knew its secrets.\"",
    bio: "Jack Stapleton lives with his sister Beryl at Merripit House. He is highly educated, seemingly calm, and spends his days hunting butterflies on the Grimpen Mire. Yet, his familiarity with the dangerous mire and his strange behavior around Baskerville Hall are deeply concerning.",
    connections: ["clue_jack_stapleton", "clue_exhibit_a4"],
  },
  {
    id: "sus_laura_lyons",
    name: "Laura Lyons",
    occupation: "Typewriting Operator",
    status: "Informant",
    threatLevel: "Medium",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC874Rcp9KTx6vonWy1w57JNjJHDeOf2q-7ZqK-t1jnlvwMeYmv7mpT6iqzmSYYR_tsYCSd16RYodGizpZqWZcqO_mkrp5AGxsicZn6sCgooCtvJdKzC80WfqdpqpDoGD1E7O6FSUDWe14GoeIhn_ANtyyWph21_72BRxcNts8z3zPpO5Bxmvk_g0w_7TGNPrJOkMedaiXflrvG7rUYSwQgeRmVIVSOiO5poF0T65LES8auzsrMmkljZRbPd6C5RCd0ydHVbVw-LrcM",
    quote: "\"I wrote to him... but I did not go to the appointment.\"",
    bio: "Daughter of the eccentric old Frankland. Abandoned by her husband, she was supported financially by Sir Charles Baskerville and Jack Stapleton. She sent a secret late-night rendezvous letter to Sir Charles on the evening he died.",
    connections: ["clue_burned_letter"],
  },
  {
    id: "sus_beryl",
    name: "Beryl Stapleton",
    occupation: "Stapleton's Sister",
    status: "Ally",
    threatLevel: "Low",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQ8u2qbeHTYvYPXb36MOW1qUR-8LTVkK54d6NmMKZ9V0NnVHwgOqQfrwwe9x3POchDC87DTI1Gl2sC3vjIqTqyinSu2NTNbKE9tpPb0z3DdLSy9IHy9tMlvfGYYYnAIem1ZuWd5WCGKNure9GtbUJhvdsiQgXfqrTm-F7iPiPoz_VMsCwnXTOePnFiaMuC6rBE8OunQ0_w0yZhmt7GrH8vRb5lJcxyVYQzYPvcv2V9ZS4GhW5Te6-oVZJj5xtT5v9QgEgG1pGgF1eF",
    quote: "\"Go back! Go straight back to London, and never set foot upon the moor again!\"",
    bio: "Outwardly known as Jack Stapleton's sister, she is a striking woman of exotic foreign descent. She gave Sir Henry a desperate anonymous warning, mistaking Dr. Watson for him. Her relationship with Jack seems heavily strained, almost hostage-like.",
    connections: ["clue_exhibit_a4"],
  },
  {
    id: "sus_barrymore",
    name: "John Barrymore",
    occupation: "Baskerville Butler",
    status: "Suspect",
    threatLevel: "Medium",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQ8u2qbeHTYvYPXb36MOW1qUR-8LTVkK54d6NmMKZ9V0NnVHwgOqQfrwwe9x3POchDC87DTI1Gl2sC3vjIqTqyinSu2NTNbKE9tpPb0z3DdLSy9IHy9tMlvfGYYYnAIem1ZuWd5WCGKNure9GtbUJhvdsiQgXfqrTm-F7iPiPoz_VMsCwnXTOePnFiaMuC6rBE8OunQ0_w0yZhmt7GrH8vRb5lJcxyVYQzYPvcv2V9ZS4GhW5Te6-oVZJj5xtT5v9QgEgG1pGgF1eF",
    quote: "\"It is not my secret to tell, sir... but it is not mischief against Sir Henry.\"",
    bio: "Barrymore was found creeping around Baskerville Hall at night, signaling with a candle from an empty window facing the moor. His wife is the sister of Selden, the escaped murderer, whom they are secretly feeding.",
    connections: ["clue_hound_footprint"],
  },
];
